## CMSE 802 Pre-class assignment: Agent-Based Model -- the Schelling Model
### Date: 09/28/2017
### Due: 10/02/2017; 11:00 PM
### Your name:
### The goal of this assignment is to use the Schelling model as an example to learn agent-based modeling. We will make some Python functions that will be used in the class. At the end of this learning module, we will reproduce the Nobel prize winning work by T. C. Schelling.

----
** Here, we take a short detour from object-oriented progamming for agent-based modeling of ant foraging.**

** The Schelling model of segregation is probably the most prominent example of agent-based modeling in social science modeling. It was introduced in 1971 (Thomas C. Schelling, Dynamic Model of Segregation, Journal of Mathematical Sociology, vol 1, 1971, pp 143--186). Because of his work on socio-economic dynamics, Schelling received the 2005 Nobel prize in Economic Sciences. **

** In the coming class, we will work on developing simulation code of the Schelling model. In this pre-class assignment, we will write some Python functions that will be used in the class. **

----
### Task 1: Let's start with watching a Youtube video introducing the Schelling model. 

In [5]:
from IPython.display import YouTubeVideo
YouTubeVideo('dFl3Cfw12bo',width=720,height=540)

# If you are interested in watch another video, uncomment the one below and watch it.
# YouTubeVideo('AZlWOykGzYg&t',width=720,height=540)

** Recall the grid label sequencing in our previous in-class assignment 2D FDM and PDE. Each grid point has a label, and indices of row and column. We will set up the checker board in a way similar to the grid system, such that each grid has a linear label, an index of row, and an index of column. **

<img src="2D-discr-3.png",width=600, height=600 />

### Task 2:
** We need to make a function that convert the label of a grid point to the indices of row and column. For example, the 99-th grid is at row = 2 and col = 1. **

In [3]:
# ##########################################################################
# function for converting linear label of grid to indices of row and column
# ##########################################################################

def Lab2Ind(n_row, n_col, lab):
    
    # complete the code
    row = lab//n_col
    col = lab - (row)*n_col 
    
    
    return row, col

** Test you function for 3675-th grid. Print the indices of row and column. **

In [4]:
# Test function Lab2Ind
import math

n_row = 99    # <== number of row
n_col = 49    # <== number of column
lab = 3675

r1, c1 = Lab2Ind(n_row, n_col, lab)

print(r1, c1)

75 0


### Task 3:
** We need to make a function that convert the indices of row and column of a grid to the linear label. For example, the grid at row = 2 and col = 1 is labeled as the 99-th point. **

In [5]:
# ##########################################################################
# function for converting row and column indices of a grid to linear label 
# ##########################################################################

def Ind2Lab(n_row, n_col, row, col):
    
    # complete the code 
    lab = n_col*(row) + col
    
    return lab

** Test you function for the grid at row = 63 and col = 23. Print the label of the grid. **

In [6]:
# Test function Lab2Ind

n_row = 99    # <== number of row
n_col = 49    # <== number of column

row = 63
col = 23

lab = Ind2Lab(n_row, n_col, row, col)

print(lab)

3110


### Task 4:
**As mentioned by Prof Page in the Youtube video, Prof Schelling did his simulations by tossing coins. For us, we will need to randomly pick numbers using computer programs. **

**We need to learn how to use Python function of np.random.permutation( ).** 

In [7]:
import numpy as np

# create a list containing 100 entries
ls = np.zeros(100)

for i in range(100):
    ls[i] = i
    
permL = np.random.permutation(ls)  # <== write a description of what this function is doing in the cell below. 

ListA = ls[0:50]
#print (len(ListA))
ListB = ls[50:80]
#print (len(ListB))
ListC = ls[80:]
#print (len(ListC))
print ("permL = ")
print (permL)
print ("ListA = ")
print (ListA)
print ("ListB = ")
print (ListB)
print ("ListC = ")
print (ListC)


permL = 
[33. 22. 29.  2. 49. 75. 91. 54. 51. 86. 72. 37. 32. 87.  1. 66. 52.  5.
 79. 21. 28. 94. 36. 24.  0.  4. 73. 89. 83. 55. 43. 41. 34. 57. 97. 56.
 96. 44. 61. 13. 88. 65. 47. 92. 81. 53. 85. 42.  8.  6. 16. 71. 60. 35.
 25. 45. 80. 40. 27. 82. 76. 62. 10. 15. 46. 26. 39. 12. 69. 38. 11. 67.
 50. 19. 31. 63. 64.  3. 14. 74. 98. 17.  7. 18. 23. 59. 93. 48. 30. 78.
 99. 90. 77. 20. 84.  9. 58. 68. 70. 95.]
ListA = 
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
ListB = 
[50. 51. 52. 53. 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67.
 68. 69. 70. 71. 72. 73. 74. 75. 76. 77. 78. 79.]
ListC = 
[80. 81. 82. 83. 84. 85. 86. 87. 88. 89. 90. 91. 92. 93. 94. 95. 96. 97.
 98. 99.]


**Your answer: ** Randomly permute a sequence, or return a permuted range.

### Now, we need to create lists of A, B, and C. List A contains the first 50 entries of permL, and List B contains the next 30 entries, and List C contains the rest of entries. Go back the code cell above, and make those three lists.  Print permL, ListA, ListB, and ListC. 

----
### Task 5:

**Now, let us create a grid system of 30 x 10. Fifty percent of the grids are occupied by species 1, and thirty percent are occupied species 2. We will use this part code to initialize the population for the Schelling model in class. **

1. Create a list of the linear labels of the grids.
1. Permute the list randomly.
1. Assign the first 50% of the entries in the randomly permuted list to species 1.
1. Assign the next 30% of the entries to species 2.
1. Plot the agents on the grids

In [2]:
import matplotlib.pyplot as plt
import random 
import numpy as np
import math


# grid system
nx = 30    # number of row
ny = 10    # number of col

grid = np.zeros((nx,ny))


# percentage of population
pct_1 = 50.                       
pct_2 = 30.   

# numbers of species 1 and 2
n_sp1 =  nx*ny*pct_1/100    # <== fill the blank
n_sp2 =  nx*ny*pct_2/100    # <== fill the blank

# linear list of grids, using permutation to randomize the list
grid_list = np.random.permutation(np.reshape(grid,-1))     # <== fill the blank
for i in range(nx):
    for j in range(ny):
        grid[i,j]=Ind2Lab(nx,ny,i,j)
grid_list = np.random.permutation(np.reshape(grid,-1))
grid_list = np.random.permutation(nx*ny)
#print (grid_list)
# linear label of the grids occupied by species 1
g_List_sp1 = grid_list[0:int(n_sp1)]    # <== fill the blank

# linear label of the grids occupied by species 2
g_List_sp2 = grid_list[int(n_sp1):int(n_sp1+n_sp2)]    # <== fill the blank


# visualization
# get the indices of row and col for the grid 

for n in range(len(g_List_sp1)):
    
    # find the indices of row and col of the agents sp1
    r1, c1 = Lab2Ind(nx, ny, g_List_sp1[n]) # <== fill the blank
    
    plt.scatter(r1, c1, color='r')


for m in range(len(g_List_sp2)):
    
    # find the indices of row and col of the agents sp2
    r2, c2 = Lab2Ind(nx, ny, g_List_sp2[m]) # <== fill the blank
    
    plt.scatter(r2, c2, color='b')    
    
plt.show()

[127 291  22 116 150  17  87   1 135   0 277 106  61 130 128 125  65  74
  84  56  29   7 192  53  15 132  72 122 198 262 159  49  54 162  93  43
 234 153 264 205 178  42 157 144  78 103 199 252 131 108 134 272  88   9
  12  94 168 225  79 185 114  39  57   2 189  24 219 158 209 281 206 287
 273  85 268 296 259 245 186 230  26 290 107 182  27 266  96 279  66  76
 113 183   3 274 239 176 246 221 136 227  34 276  20 101 232 233 270 165
  14 210 142 237 145   5 261 196 223 126  99 118 111 129 188 139  64  45
 184 285  19   4 207 109 172  40 236 226 161  81 208  36  46  90  92  83
 293 137  86  89 201 190 170  50 254 222 138  77 244  95 271  68 240  28
 229 200 298 195  31 180 214 105  98 187  51 110   6 292 243 133 167 267
 151 286 278 147 283  11 269  30  32 288 295 160   8 213 216 265 175 260
  47  21 181 248 297 238  91 241 104  97 194 289 143 148 202  10 231  69
  33  73 100 249  75 282 179 263 242 156 294 120  58 251 146 155  82 212
 166 102 280  23 193 203  18  38 224 177 112 247 15

NameError: name 'Lab2Ind' is not defined

### Assignment wrap-up

**What questions do you have, if any, about any of the topics discussed in this assignment.**

**Put your answer here!**

**Do you have any further questions or comments about this material?**

**Put your answer here!**

### Congratulations, you're done with your first pre-class assignment!

Now, you just need to submit this assignment by uploading it to the course Desire2Learn web page.  Go to Assessments > Dropbox, find the link for Pre-class assignment 20170925, and upload it there.

**Please keep a copy the code. We will reuse the code in the class.**

See you in class!

In [18]:
import numpy as np
import math

def LabelToIndices(n_row, n_col, lab):
    row = lab//n_col
    col = lab - row*n_col
    return row, col


# percentage of population
pct_1 = 50.                       # houses occupied by species 1
pct_2 = 40.                       # houses occupied by species 2
pct_e = 100. - pct_1 - pct_2      # empty houses

# moving criterion
mvcr = 0.5

# grid system
nx = 99    # number of column
ny = 49    # number of row
grid_com = np.zeros((nx,ny))

n_sp1 = int(nx*ny*pct_1/100)       # number of houses occupied by sp1
n_sp2 = int(nx*ny*pct_2/100)       # number of houses occupied by sp2
n_emp = nx*ny - n_sp1 - n_sp2      # number of empty houses


# linear list of grids, using permutation to randomize the list
grid_list = np.random.permutation(nx*ny)

# initial distribution: each grid point is occupied by either sp1, sp2, or empty (idnt = 3)
# (1) You can assign the first group (number of sp1) in the permuted list to sp1
# (2) Find the row and column of the grids in that group
# (3) Assign the value of grid_com[row, col] equal = 1 on the corresponding grids occupied by sp1
# (4) Do the same for grids for sp2 and empty
# loop over all grids


for i in range(nx*ny):
    # put you code here
    if i<n_sp1:
        row, col = LabelToIndices(nx,ny,grid_list[i])
        grid_com[row, col] = 1
    elif n_sp1<=i<n_sp1+n_sp2:
        row, col = LabelToIndices(nx,ny,grid_list[i])
        grid_com[row, col] = 2
    else:
        
        row, col = LabelToIndices(nx,ny,grid_list[i])
        grid_com[row, col] = 3
    
print(grid_com)   

[[1. 1. 1. ... 3. 1. 1.]
 [1. 1. 2. ... 1. 2. 2.]
 [2. 2. 1. ... 2. 1. 3.]
 ...
 [3. 1. 1. ... 1. 1. 2.]
 [2. 2. 2. ... 1. 1. 1.]
 [1. 2. 2. ... 2. 1. 1.]]


In [20]:
grid_gh = np.zeros((nx+2,ny+2))     # <== fill the blank; The dimension of the new grid system.
grid_gh[1:nx+1,1:ny+1] = grid_com[0:nx,0:ny]
print (grid_gh)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 2. 2. 0.]
 ...
 [0. 2. 2. ... 1. 1. 0.]
 [0. 1. 2. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
